server:
  port: 8080
  # 测试阶段先不使用
  servlet:
    context-path: /wxWGSJ

Spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/wgsj?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username:        # 数据库用户名
    password:    # 数据库密码
#     driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 3000
      LoginTimeout: 60000

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.whu.WGSJ_Server.domain

xcloud:
  uploadPath: E:/attach_file/wxWGSJ/
  staticPath: resources

logging:
  level:
    com.whu.netemer.mapper: info
    jdbc:
      audit: error
      resultset: error
      connection: error

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: 127.0.0.1  # Redis本地服务器地址
    port: 6379       # Redis服务器连接端口
#    password:   # Redis服务器连接密码（默认为空）
    timeout: 0       # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0    # 连接池中的最小空闲连接
